/**********************************************************************
 * Notas de Riesgos Financieros;
 * Jose Enrique Perez ;
 * Licenciatura en Actuaría;
 * Facultad de Negocios. Universidad La Salle México;
 **********************************************************************/

/************************/
/* Importación de datos */
/************************/

/* Generated Code (IMPORT) */
/* Source File: credit_risk_dataset.csv */
/* Source Path: /shared/home/perez-jose@lasallistas.org.mx/riesgos_financieros/credit_risk_dataset.csv */
/* Code generated on: Oct 4, 2022, 10:47:09 AM */

proc sql;
%if %sysfunc(exist(WORK.IMPORT)) %then %do;
    drop table WORK.IMPORT;
%end;
%if %sysfunc(exist(WORK.IMPORT,VIEW)) %then %do;
    drop view WORK.IMPORT;
%end;
quit;



FILENAME REFFILE DISK '/shared/home/perez-jose@lasallistas.org.mx/riesgos_financieros/credit_risk_dataset.csv';

PROC IMPORT DATAFILE=REFFILE
	DBMS=CSV
	OUT=WORK.IMPORT;
	GETNAMES=YES;
RUN;

PROC CONTENTS DATA=WORK.IMPORT; RUN;


/*************************/
/* Análisis exploratorio */
/*************************/

/* 
 * 
 * Task code generated by SAS® Studio 5.2
 * 
 * Generated on '10/4/22, 12:09 PM'
 * Generated by 'perez-jose@lasallistas.org.mx'
 * Generated on server 'pdcesx23077'
 * Generated on SAS platform 'Linux LIN X64 3.10.0-1160.42.2.el7.x86_64'
 * Generated on SAS version 'V.03.05M0P111119'
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36'
 * Generated on web client 'https://v4e081.vfe.sas.com/SASStudioV/main?locale=en&launchedFromAppSwitcher=true'
 */

options validvarname=any;
ods noproctitle;
ods graphics / imagemap=on;

proc sort data=WORK.IMPORT out=WORK.TempSorted5215;
	by loan_status;
run;

/* Scatter plot matrix macro */
%macro scatterPlotMatrix(xVars=, title=, groupVar=);
	proc sgscatter data=WORK.TempSorted5215;
		matrix &xVars / %if(&groupVar ne %str()) %then
			%do;
				group=&groupVar legend=(sortorder=ascending) %end;
		diagonal=(histogram);
		title &title;
		by loan_status;
	run;

	title;
%mend scatterPlotMatrix;

/* Histogram (one-way or two-way) */
%macro DEHisto(data=, avar=, classVar=);
	%local i numAVars numCVars cVar cVar1 cVar2;
	%let numAVars=%Sysfunc(countw(%str(&avar), %str( ), %str(q)));
	%let numCVars=%Sysfunc(countw(%str(&classVar), %str( ), %str(q)));

	%if(&numAVars>0 & &numCVars>0) %then
		%do;

			%if(&numCVars=1) %then
				%do;
					%let cVar=%scan(%str(&classVar), 1, %str( ), %str(q));

					proc sql noprint;
						select count(distinct &cVar) into :nrows from &data;
					quit;

					/* One-way histogram */
					proc univariate data=&data noprint;
						var &avar;
						class &cVar;
						histogram &avar / nrows=&nrows;
					run;

				%end;
			%else
				%do;

					/* One-way histogram of each class variable */
                
					%do i=1 %to %eval(&numCVars);
						%let cVar=%scan(%str(&classVar), &i, %str( ), %str(q));

						proc sql noprint;
							select count(distinct &cVar) into :nrows from &data;
						quit;

						proc univariate data=&data noprint;
							var &avar;
							class &cVar;
							histogram &avar / nrows=&nrows;
						run;

					%end;

					/* Two-way histogram */
                %let cVar1=%scan(%str(&classVar), 1, %str( ), 
						%str(q));
					%let cVar2=%scan(%str(&classVar), 2, %str( ), %str(q));

					proc sql noprint;
						select count(distinct &cVar1) into :nrows from &data;
					quit;

					proc sql noprint;
						select count(distinct &cVar2) into :ncols from &data;
					quit;

					proc univariate data=&data noprint;
						var &avar;
						class &cVar1 &cVar2;
						histogram &avar / nrows=&nrows ncols=&ncols;
					run;

				%end;
		%end;
%mend DEHisto;

/* By group histogram (one-way or two-way) */
%macro byGroupDEHisto(data=, level=, num_level=, byVars=, num_byvars=, avar=, 
		classVar=);
	%local i j dsid whereClause varnum rc groupInfo;

	%do j=1 %to &num_byvars;
		%let varName&j=%scan(%str(&byVars), &j);
	%end;

	%do i=1 %to &num_level;

		/* Get group variable values. */
		data _null_;
			i=&i;
			set &level point=i;

			%do j=1 %to &num_byvars;
				call symputx("x&j", strip(&&varName&j), 'l');
			%end;
			stop;
		run;

		/* Build proc sql where clause. */
        %let dsid=%sysfunc(open(&data));
		%let whereClause=;

		%do j=1 %to %eval(&num_byvars-1);
			%let varnum=%sysfunc(varnum(&dsid, &&varName&j));

			%if(%sysfunc(vartype(&dsid, &varnum))=C) %then
				%let whereClause=&whereClause.&&varName&j.="&&x&j"%str( and );
			%else
				%let whereClause=&whereClause.&&varName&j.=&&x&j.%str( and );
		%end;
		%let varnum=%sysfunc(varnum(&dsid, &&varName&num_byvars));

		%if(%sysfunc(vartype(&dsid, &varnum))=C) %then
			%let whereClause=&whereClause.&&varName&num_byvars.="&&x&num_byvars";
		%else
			%let whereClause=&whereClause.&&varName&num_byvars.=&&x&num_byvars;
		%let rc=%sysfunc(close(&dsid));

		/* Subsetting the data set. */
		proc sql noprint;
			create table WORK.tempData as select * from &data
        where &whereClause;
		quit;

		/* Build plot group info. */
        %let groupInfo=;

		%do j=1 %to %eval(&num_byvars-1);
			%let groupInfo=&groupInfo.&&varName&j.=&&x&j%str( );
		%end;
		%let groupInfo=&groupInfo.&&varName&num_byvars.=&&x&num_byvars;

		/* Create by group Histogram. */
		title (&groupInfo);
		%DEHisto(data=WORK.tempData, avar=&avar, classVar=&classVar);
		title;
	%end;
%mend byGroupDEHisto;

%scatterPlotMatrix(xVars=person_age person_income person_emp_length loan_amnt 
	loan_int_rate loan_percent_income, 
	title="Scatter plot matrix grouped by person_home_ownership", 
	groupVar=person_home_ownership);
%scatterPlotMatrix(xVars=person_age person_income person_emp_length loan_amnt 
	loan_int_rate loan_percent_income, 
	title="Scatter plot matrix grouped by loan_intent", groupVar=loan_intent);
%let num_level=0;

data WORK.level(keep=loan_status unique_level);
	set WORK.TempSorted5215 end=lastobs;
	retain unique_level 0;
	by loan_status;

	if last.loan_status then
		do;
			unique_level+1;
			output;
		end;

	if lastobs then
		call symputx('num_level', strip(put(unique_level, best.)), 'l');
run;

%byGroupDEHisto(data=WORK.TempSorted5215, level=WORK.level, 
	num_level=&num_level, byVars=loan_status, num_byvars=1, avar=person_age 
	person_income person_emp_length loan_amnt loan_int_rate loan_percent_income, 
	classVar=person_home_ownership loan_intent);

proc sort data=WORK.IMPORT out=WORK.TempSorted4877;
	by loan_status person_home_ownership;
run;

proc boxplot data=WORK.TempSorted4877;
	plot (person_age person_income person_emp_length loan_amnt loan_int_rate 
		loan_percent_income)*person_home_ownership / boxstyle=schematic;
	by loan_status;
run;

proc sort data=WORK.IMPORT out=WORK.TempSorted4877;
	by loan_status loan_intent;
run;

proc boxplot data=WORK.TempSorted4877;
	plot (person_age person_income person_emp_length loan_amnt loan_int_rate 
		loan_percent_income)*loan_intent / boxstyle=schematic;
	by loan_status;
run;

proc datasets library=WORK noprint;
	delete TempSorted5215 level tempData TempSorted4877;
	run;

/* 
 * 
 * Task code generated by SAS® Studio 5.2
 * 
 * Generated on '10/4/22, 12:13 PM'
 * Generated by 'perez-jose@lasallistas.org.mx'
 * Generated on server 'pdcesx23077'
 * Generated on SAS platform 'Linux LIN X64 3.10.0-1160.42.2.el7.x86_64'
 * Generated on SAS version 'V.03.05M0P111119'
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36'
 * Generated on web client 'https://v4e081.vfe.sas.com/SASStudioV/main?locale=en&launchedFromAppSwitcher=true'
 */

ods noproctitle;
ods graphics / imagemap=on;

proc sort data=WORK.IMPORT out=WORK.TempSorted2236;
	by loan_status;
run;

proc means data=WORK.TempSorted2236 chartype mean std min max n nmiss stderr 
		vardef=df;
	var person_age person_income person_emp_length loan_amnt loan_int_rate 
		loan_percent_income cb_person_cred_hist_length;
	class person_home_ownership loan_intent loan_grade cb_person_default_on_file;
	by loan_status;
run;

proc sort data=WORK.IMPORT out=WORK.TempSorted2236;
	by loan_status person_home_ownership;
run;

proc boxplot data=WORK.TempSorted2236;
	plot (person_age person_income person_emp_length loan_amnt loan_int_rate 
		loan_percent_income cb_person_cred_hist_length)*person_home_ownership / 
		boxstyle=schematic;
	inset mean stddev min max nobs / position=nw;
	insetgroup mean stddev min max n / position=top;
	by loan_status;
run;

proc sort data=WORK.IMPORT out=WORK.TempSorted2236;
	by loan_status loan_intent;
run;

proc boxplot data=WORK.TempSorted2236;
	plot (person_age person_income person_emp_length loan_amnt loan_int_rate 
		loan_percent_income cb_person_cred_hist_length)*loan_intent / 
		boxstyle=schematic;
	inset mean stddev min max nobs / position=nw;
	insetgroup mean stddev min max n / position=top;
	by loan_status;
run;

proc sort data=WORK.IMPORT out=WORK.TempSorted2236;
	by loan_status loan_grade;
run;

proc boxplot data=WORK.TempSorted2236;
	plot (person_age person_income person_emp_length loan_amnt loan_int_rate 
		loan_percent_income cb_person_cred_hist_length)*loan_grade / 
		boxstyle=schematic;
	inset mean stddev min max nobs / position=nw;
	insetgroup mean stddev min max n / position=top;
	by loan_status;
run;

proc sort data=WORK.IMPORT out=WORK.TempSorted2236;
	by loan_status cb_person_default_on_file;
run;

proc boxplot data=WORK.TempSorted2236;
	plot (person_age person_income person_emp_length loan_amnt loan_int_rate 
		loan_percent_income cb_person_cred_hist_length)*cb_person_default_on_file / 
		boxstyle=schematic;
	inset mean stddev min max nobs / position=nw;
	insetgroup mean stddev min max n / position=top;
	by loan_status;
run;

proc datasets library=WORK noprint;
	delete TempSorted2236;
	run;


/***********************/
/* Regresión logística */
/***********************/

/* 
 * 
 * Task code generated by SAS® Studio 5.2
 * 
 * Generated on '10/4/22, 11:09 AM'
 * Generated by 'perez-jose@lasallistas.org.mx'
 * Generated on server 'pdcesx23077'
 * Generated on SAS platform 'Linux LIN X64 3.10.0-1160.42.2.el7.x86_64'
 * Generated on SAS version 'V.03.05M0P111119'
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36'
 * Generated on web client 'https://v4e081.vfe.sas.com/SASStudioV/main?locale=en&launchedFromAppSwitcher=true'
 */

ods noproctitle;
ods graphics / imagemap=on;

proc logistic data=WORK.IMPORT plots=(roc);
	class person_home_ownership loan_intent loan_grade cb_person_default_on_file / 
		param=glm;
	model loan_status(event='1')=person_home_ownership loan_intent loan_grade 
		cb_person_default_on_file person_age person_income person_emp_length 
		loan_amnt loan_int_rate loan_percent_income cb_person_cred_hist_length / 
		link=logit ctable technique=fisher;
	score out=work.Logistic_scores;
run;
